name       : flow-pomodoro
version    : 1.2.0
release    : 4
source     :
    - https://github.com/iamsergio/flow-pomodoro/archive/v1.2.0.tar.gz : 7b3389aec5400b027403c86984f432436b8c25f492c9077ba8a09521632daaf7
license    : GPL-2.0-or-later
component  : office
summary    : A pomodoro app that blocks distractions while you work.
description: |
    A pomodoro app that blocks distractions while you work.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Qml)
    - qt5-quickcontrols
rundeps    :
    - qt5-quickcontrols
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-icon.patch
    %qmake .
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    install -Dm00644 flow.desktop $installdir/usr/share/applications/flow.desktop
    install -Dm00644 src/img/icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/flow.svg
